/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddbbclassicmodel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarda
 */
public class altaEmpleado extends javax.swing.JFrame {
private String numeroE;
    /**
     * Creates new form altaEmpleado
     */
    public altaEmpleado() {
        initComponents();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxOfficeCode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jComboBoxOfficeCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------" }));

        jButton1.setText("ALTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("VOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("EMAIL:");

        jLabel4.setText("Office Code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApellido)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jComboBoxOfficeCode, 0, 133, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOfficeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed
public void cargarComboBox(){
    String vSQL = new String();
        String[] registro = new String[4];

     

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT DISTINCT officeCode FROM offices NATURAL JOIN employees";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
              jComboBoxOfficeCode.addItem(rs.getString(1));
            
            }
         
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
    
}

public String conseguirNumE(){
    
    String vSQL = new String();
        String[] registro = new String[4];

     

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT MAX(employeeNumber) FROM employees";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
              numeroE=rs.getString(1);
            int num=Integer.parseInt(numeroE);
            num++;
            numeroE=""+num;
            }
         
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
    return numeroE;
}

public String extension(){
     String vSQL = new String();
        String[] registro = new String[4];
String numC="";
     

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT MAX(extension) FROM employees";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
              numeroE=rs.getString(1);
                System.out.println(numeroE);
              for(int i=1;i<numeroE.length();i++){
                numC+=numeroE.charAt(i);
              }
                System.out.println(numC+"despues del for"); 
            int num=Integer.parseInt(numC);
            num++;
                System.out.println("despues del `++"+num);
            numeroE="x"+num;
            }
            System.out.println("despues del X"+numeroE);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
    return numeroE;
    
  
}
public boolean emailValidar(String email){
    // Patrón para validar el email
    String val=email;
    boolean correcto=false;
		Pattern pattern = Pattern
				.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
						+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

		// El email a validar
		//String email = "info@programacionextrema.com";
               
		Matcher mather = pattern.matcher(val);

		if (mather.find() == true) {
			//JOptionPane.showMessageDialog(this, "EMAIL VALIDO");
                        correcto=true;
		} else {
		JOptionPane.showMessageDialog(this, "EMAIL NO-VALIDO");
                        correcto=false;
		}
    return correcto;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean emailValid=false;
       int officeCode;
       String reportsTo="";
       officeCode=jComboBoxOfficeCode.getSelectedIndex();
       String numeroEmpleado=conseguirNumE();
       String jobTitle="Sales Rep";
       String extension=extension();
      String nombre=jTextFieldNombre.getText();
       String apellido=jTextFieldApellido.getText();
       
       
      String email=jTextFieldEmail.getText();
      
      if(emailValidar(email)){
          emailValid=true;
      }
       switch(officeCode){
               case 1: reportsTo="1143";
               break;
               case 2:reportsTo="1056";
               break;
               case 3:reportsTo="1056";
               break;
               case 4:reportsTo="1102";
               break;
               case 5:reportsTo="1621";
               break;
               case 6:reportsTo="1088";
               break;
               case 7:reportsTo="1056";
               break;
               default:
                   break;            
               
       }
       
       
        String vSQL = new String();
        String[] registro = new String[4];

     

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
if(emailValid){
        vSQL = "INSERT INTO employees (employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle)VALUES('"+numeroEmpleado+"','"+nombre+"','"+apellido+"','"+extension+"','"+email+"','"+officeCode+"','"+reportsTo+"','"+jobTitle+"')";// esto es lo que cambia
}else{
    JOptionPane.showMessageDialog(this, "ERROR INESPERADO");
}
        try {
            Statement st = cn.createStatement();
            int rs = st.executeUpdate(vSQL);
           //st.executeQuery(vSQL);
            if (rs==1) {
                 System.out.println(numeroEmpleado);
             JOptionPane.showMessageDialog(this, "ALTA CORRECTA");
     
            }else{
               JOptionPane.showMessageDialog(this, "NO SE HA PODIDO DAR DE ALTA");
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxOfficeCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
