/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddbbclassicmodel;

import Estructura.Producto;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tarda
 */
public class classicmodels extends javax.swing.JFrame {
    private static ArrayList<Producto> carrito=new ArrayList();
DefaultTableModel modelo;
LoginPrincipal lp;

    public static ArrayList<Producto> getCarrito() {
        return carrito;
    }

   
private String nombreUser;
    /**
     * Creates new form General
     */
    public classicmodels() {
        initComponents();
       nombreUser=lp.getNomUserL();
       jLabelEmailUser.setText(nombreUser);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmailUser = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jLabelProducto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonAceptarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonVerProductos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxTipos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelEmailUser.setText("fggdgfdf");

        jTextFieldCantidad.setText("10");
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jLabelProducto.setText("Producto cantidad:");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldBuscar.setText("Buscar...");
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });

        jButtonAceptarBusqueda.setText("GO");
        jButtonAceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarBusquedaActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jButtonCarrito.setText("Ver Carrito");
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar producto por nombre:");

        jButtonVerProductos.setText("VER TODOS PRODUCTOS");
        jButtonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProductosActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Tipo", "Classic Cars", "Motorcycles", "Planes", "Ships", "Trains", "Trucks & Buses", "Vintage Cars" }));
        jComboBoxTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposActionPerformed(evt);
            }
        });

        jLabel2.setText("Ver Productos por tipo:");

        jLabel3.setText("Nombre Usuario:");

        jButton3.setText("CERRAR SESION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmailUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCarrito))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAceptarBusqueda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonMenos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMas))
                                    .addComponent(jButton1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVerProductos)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCarrito)
                            .addComponent(jButtonVerProductos))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelEmailUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAceptarBusqueda))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProducto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMas)
                                    .addComponent(jButtonMenos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
        
        int cantidad;
        String cant;
        
       cant=jTextFieldCantidad.getText();
       cantidad=Integer.parseInt(cant);
       if(cantidad<=0){
           jTextFieldCantidad.setText("0");
       }else{
       cantidad--;
       jTextFieldCantidad.setText(cantidad+"");
       }
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
        int cantidad;
        String cant;
       cant=jTextFieldCantidad.getText();
       cantidad=Integer.parseInt(cant);
       cantidad++;
       jTextFieldCantidad.setText(cantidad+"");
       
        
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila;
       int cantidad;
   
        String vNif=null;
        String vPrecio=null;
        double precio=0;
        String cant=jTextFieldCantidad.getText();
        int control=Integer.parseInt(cant);
        try {          
           fila=jTableProductos.getSelectedRow();

            if (fila==-1 || control<=0)
            {
                if(control==0){
                    JOptionPane.showMessageDialog(null,"SELECCIONA UNA CANTIDAD");
                }else{
                JOptionPane.showMessageDialog(null,"NINGUN PRODUCTO SELECCIONADO");
                }
            }
            else{
             
              vNif=(String) jTableProductos.getValueAt(fila,0);
              vPrecio=(String) jTableProductos.getValueAt(fila,3);
              precio=Double.parseDouble(vPrecio);
              cantidad=Integer.parseInt(jTextFieldCantidad.getText());
            
           
           Producto p=new Producto(vNif,cantidad,precio);
            
            carrito.add(p);
            JOptionPane.showMessageDialog(null, p.toStringJPane());
            jTextFieldCantidad.setText("0");
            }
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarBusquedaActionPerformed
        // TODO add your handling code here:
        String busqueda;
        busqueda=jTextFieldBuscar.getText();
        
         String[] titols = {"Nombre Producto","Descripcion", "Stock","Precio"};
        String vSQL = new String();
        String[] registro = new String[4];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectarCustomer();

        vSQL = "SELECT productName,productDescription, quantityInStock,MSRP FROM products WHERE productName LIKE '%"+busqueda+"%'";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("productName");
                registro[1] = rs.getString("productDescription");
                registro[2] = rs.getString("quantityInStock");
                registro[3] = rs.getString("MSRP");
                

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
        
    }//GEN-LAST:event_jButtonAceptarBusquedaActionPerformed

    private void jButtonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProductosActionPerformed
        // TODO add your handling code here:
        consultarProductos();
    }//GEN-LAST:event_jButtonVerProductosActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        // TODO add your handling code here:
        jTextFieldBuscar.setText("");
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        // TODO add your handling code here:
        VerCarrito vc=new VerCarrito();
        vc.setVisible(true);
        
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jComboBoxTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposActionPerformed
        // TODO add your handling code here:
        //String[] titols = {"PRODUCTCODE", "PRODUCTNAME", "PRODUCTLINE", "PRODUCTSCALE","PRODUCTVENDOR","PRODUCTDESCRIPTION","QUANTITYINSTOCK","BUYPRICE","MSRP"};
        String[] titols = {"Nombre Producto","Descripción", "Stock","Precio"};
        String vSQL = new String();
        String[] registro = new String[4];
 jComboBoxTipos.getSelectedIndex();
 String tipo=null;
            switch(jComboBoxTipos.getSelectedIndex()){
                case 1: tipo="Classic Cars";
                    break;
                case 2: tipo="Motorcycles";
                    break;
                case 3:tipo="Planes";
                    break;
                    case 4: tipo="Ships";
                    break;
                case 5:tipo="Trains";
                    break;
                case 6:tipo="Trucks and Buses";
                    break;
                case 7:tipo="Vintage Cars";
                    break;
                default:
                    break;
                
            }
        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectarCustomer();

        vSQL = "SELECT productName,productDescription,quantityInStock,MSRP FROM products WHERE productLine='"+tipo+"'";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("productName");
                registro[1] = rs.getString("productDescription");
                registro[2] = rs.getString("quantityInStock");
                registro[3] = rs.getString("MSRP");
                

                modelo.addRow(registro);
            }
           
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_jComboBoxTiposActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            
            LoginPrincipal llpp=new LoginPrincipal();
            
            llpp.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(classicmodels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(classicmodels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(classicmodels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(classicmodels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(classicmodels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new classicmodels().setVisible(true);
            }
        });
    }
      
    public void consultarProductos() {

        //String[] titols = {"PRODUCTCODE", "PRODUCTNAME", "PRODUCTLINE", "PRODUCTSCALE","PRODUCTVENDOR","PRODUCTDESCRIPTION","QUANTITYINSTOCK","BUYPRICE","MSRP"};
        String[] titols = {"Nombre Producto","Descripción", "Stock","Precio"};
        String vSQL = new String();
        String[] registro = new String[4];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectarCustomer();

        vSQL = "SELECT productName,productDescription,quantityInStock,MSRP FROM products";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("productName");
                registro[1] = rs.getString("productDescription");
                registro[2] = rs.getString("quantityInStock");
                registro[3] = rs.getString("MSRP");
                

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAceptarBusqueda;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonVerProductos;
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmailUser;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
