/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddbbclassicmodel;

import Estructura.Producto;
import java.awt.Font;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.StyleConstants.FontFamily;
/**
 *
 * @author Tarda
 */
public class empleadoJefeSupremo extends javax.swing.JFrame {
    private static ArrayList<Producto> carrito=new ArrayList();
DefaultTableModel modelo;
LoginPrincipal lp;
private String numBoss;
private static String orderM;


    public static String getOrderM() {
        return orderM;
    }


    public static ArrayList<Producto> getCarrito() {
        return carrito;
    }

   
private String nombreUser;
    /**
     * Creates new form General
     */
    public empleadoJefeSupremo() {
        initComponents();
       nombreUser=lp.getNomUserL();
       jLabelEmailUser.setText(nombreUser);
       //cargarVentasE();
        System.out.println(nombreUser);
        jButtonCarrito.setEnabled(false);
        jButton1.setEnabled(false);
         jButtonMas.setEnabled(false);
        jButtonMenos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmailUser = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jLabelProducto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonAceptarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonCarrito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonVerProductos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBoxTipos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelEmailUser.setText("fggdgfdf");

        jTextFieldCantidad.setText("0");
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jLabelProducto.setText("Producto cantidad:");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldBuscar.setText("Buscar...");
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });

        jButtonAceptarBusqueda.setText("GO");
        jButtonAceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarBusquedaActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jButtonCarrito.setText("Ver Carrito");
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar producto por nombre:");

        jButtonVerProductos.setText("VER TODOS PRODUCTOS");
        jButtonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProductosActionPerformed(evt);
            }
        });

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Tipo", "Classic Cars", "MotorCycle", "Planes", "Ships", "Trains", "Trucks & Buses", "Vintage Cars" }));
        jComboBoxTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTiposActionPerformed(evt);
            }
        });

        jLabel2.setText("Ver Productos por tipo:");

        jLabel3.setText("Nombre Usuario:");

        jButton3.setText("ELIMINAR EMPLEADO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ALTA EMPLEADO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("VER COMPRAS DE MIS CLIENTES");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText("CONSULTAR MIS CLIENTES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("VER AVISOS PENDIENTES");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("LIMPIAR AVISOS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("MODIFICAR COMPRA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("CERRAR SESION");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmailUser)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAceptarBusqueda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonMenos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonMas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton1))))
                            .addComponent(jButtonVerProductos)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(2, 2, 2)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCarrito))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelEmailUser)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButtonCarrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAceptarBusqueda))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVerProductos)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProducto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMas)
                                    .addComponent(jButtonMenos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
        
        int cantidad;
        String cant;
        
       cant=jTextFieldCantidad.getText();
       cantidad=Integer.parseInt(cant);
       if(cantidad<=0){
           jTextFieldCantidad.setText("0");
       }else{
       cantidad--;
       jTextFieldCantidad.setText(cantidad+"");
       }
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
        int cantidad;
        String cant;
       cant=jTextFieldCantidad.getText();
       cantidad=Integer.parseInt(cant);
       cantidad++;
       jTextFieldCantidad.setText(cantidad+"");
       
        
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila;
       int cantidad;
   
        String vNif=null;
        String vPrecio=null;
        double precio=0;
        String cant=jTextFieldCantidad.getText();
        int control=Integer.parseInt(cant);
        try {          
           fila=jTableProductos.getSelectedRow();

            if (fila==-1 || control<=0)
            {
                if(control==0){
                    JOptionPane.showMessageDialog(null,"SELECCIONA UNA CANTIDAD");
                }else{
                JOptionPane.showMessageDialog(null,"NINGUN PRODUCTO SELECCIONADO");
                }
            }
            else{
             
              vNif=(String) jTableProductos.getValueAt(fila,0);
              vPrecio=(String) jTableProductos.getValueAt(fila,3);
              precio=Double.parseDouble(vPrecio);
              cantidad=Integer.parseInt(jTextFieldCantidad.getText());
            
           
           Producto p=new Producto(vNif,cantidad,precio);
            
            carrito.add(p);
            JOptionPane.showMessageDialog(null, p.toStringJPane());
            jTextFieldCantidad.setText("0");
            }
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarBusquedaActionPerformed
        // TODO add your handling code here:
        String busqueda;
        busqueda=jTextFieldBuscar.getText();
        
         String[] titols = {"ID", "Fecha pedido","Fecha requerida","Fecha envio","Estado","Comentarios"};
        String vSQL = new String();
        String[] registro = new String[6];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT orderNumber, orderDate, requiredDate,shippedDate,`status`,comments FROM orders \n" +
"NATURAL JOIN customers JOIN employees ON employeeNumber=salesRepEmployeeNumber\n" +
" WHERE employees.firstName='"+nombreUser+"' ORDER BY orderDate DESC";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString(1);
                registro[1] = rs.getString(2);
                registro[2] = rs.getString(3);
                registro[3] = rs.getString(4);
                registro[4] = rs.getString(5);
                registro[5] = rs.getString(6);
                

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
        
    }//GEN-LAST:event_jButtonAceptarBusquedaActionPerformed
public void cargarVentasE(){

        
         String[] titols = {"ID", "Fecha pedido","Fecha requerida","Fecha envio","Estado","Comentarios"};
        String vSQL = new String();
        String[] registro = new String[6];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT orderNumber, orderDate, requiredDate,shippedDate,status,comments FROM orders NATURAL JOIN customers JOIN employees ON salesRepEmployeeNumber=employeeNumber WHERE employees.firstName='"+nombreUser+"' ORDER BY orderDate";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("orderNumber");
                registro[1] = rs.getString(2);
                registro[2] = rs.getString(3);
                registro[3] = rs.getString(4);
                registro[4] = rs.getString(5);
                registro[5] = rs.getString(6);
                

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
   
}
    private void jButtonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProductosActionPerformed
        // TODO add your handling code here:
        consultarProductos();
    }//GEN-LAST:event_jButtonVerProductosActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        // TODO add your handling code here:
        jTextFieldBuscar.setText("");
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        // TODO add your handling code here:
        VerCarrito vc=new VerCarrito();
        vc.setVisible(true);
        
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jComboBoxTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTiposActionPerformed
        // TODO add your handling code here:
        //String[] titols = {"PRODUCTCODE", "PRODUCTNAME", "PRODUCTLINE", "PRODUCTSCALE","PRODUCTVENDOR","PRODUCTDESCRIPTION","QUANTITYINSTOCK","BUYPRICE","MSRP"};
        String[] titols = {"Nombre Producto","Descripción", "Stock","Precio"};
        String vSQL = new String();
        String[] registro = new String[4];
 jComboBoxTipos.getSelectedIndex();
 String tipo=null;
            switch(jComboBoxTipos.getSelectedIndex()){
                case 1: tipo="Classic Cars";
                    break;
                case 2: tipo="Motorcycles";
                    break;
                case 3:tipo="Planes";
                    break;
                    case 4:tipo="Ships";
                    break;
                case 5:tipo="Trains";
                    break;
                case 6:tipo="Trucks and Buses";
                    break;
                case 7:tipo="Vintage Cars";
                    break;
                default:
                    break;
                
            }
        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT productName,productDescription,quantityInStock,buyPrice FROM products WHERE productLine='"+tipo+"'";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("productName");
                registro[1] = rs.getString("productDescription");
                registro[2] = rs.getString("quantityInStock");
                registro[3] = rs.getString("buyPrice");
                

                modelo.addRow(registro);
            }
           
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_jComboBoxTiposActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String idE=JOptionPane.showInputDialog("INTRODUCE EL EMPLOYEENUMBER");
        
        
        
        String vSQL = new String();
        String[] registro = new String[7];

     //   modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "DELETE FROM employees WHERE employeeNumber='"+idE+"'";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            int rs = st.executeUpdate(vSQL);
           //st.executeQuery(vSQL);
            if (rs==1) {
                 
             JOptionPane.showMessageDialog(this, "USUARIO ELIMINADO");
            
                     
             
     
            }else{
                 JOptionPane.showMessageDialog(this, "NO SE HA PODIDO ELIMINAR USUARIO");
            }
           
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
        
     
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        altaEmpleado ae=new altaEmpleado();
        ae.setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        cargarVentasE();
    }//GEN-LAST:event_jButton7ActionPerformed

     public void cargarUsersDeEmpleado(String id){
        String idConsult="";
        idConsult=id;
        
         String[] titols = { "customerName", "contactLastName", "contactFirstName", "phone", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "creditLimit"};
        String vSQL = new String();
        String[] registro = new String[11];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT  customerName, contactLastName, contactFirstName, phone, addressLine1, addressLine2, city, state, postalCode, country, creditLimit  FROM  customers JOIN employees ON salesRepEmployeeNumber=employeeNumber WHERE employees.firstName='"+nombreUser+"' AND customerNumber='"+idConsult+"';";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            if (rs.next()) {
                registro[0] = rs.getString(1);
                registro[1] = rs.getString(2);
                registro[2] = rs.getString(3);
                registro[3] = rs.getString(4);
                registro[4] = rs.getString(5);
                registro[5] = rs.getString(6);
                registro[6] = rs.getString(7);
                registro[7] = rs.getString(8);
                registro[8] = rs.getString(9);
                registro[9] = rs.getString(10);
                registro[10] = rs.getString(11);
               // registro[11] = rs.getString(12);
               
           

                modelo.addRow(registro);
            }else{
                JOptionPane.showMessageDialog(lp, "CustomerNumber WRONG!!!");
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
     }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         String idConsult=JOptionPane.showInputDialog("Introduce el CustomerNumber que quieras consultar");
        System.out.println(idConsult);
        cargarUsersDeEmpleado(idConsult);
        
    }//GEN-LAST:event_jButton5ActionPerformed
 public void cargarAvisoUser(){
        
       
        
         String[] titols = { "ID", "Num. empleado", "Num Cliente", "Num. JEFE", "Comments"};
        String vSQL = new String();
        String[] registro = new String[6];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT  idLog, logA.employeeNumber, customerNumber, boss, comments, avisado FROM logA NATURAL JOIN customers NATURAL JOIN employees WHERE boss=(SELECT employeeNumber FROM employees WHERE employees.firstName='"+nombreUser+"') AND avisado=0;";
               
               

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while(rs.next()) {
                registro[0] = rs.getString(1);
                registro[1] = rs.getString(2);
                registro[2] = rs.getString(3);
                registro[3] = rs.getString(4);
                numBoss=rs.getString(4);
                registro[4] = rs.getString(5);
              // String con = rs.getString(6);
             //  if(con.contentEquals("1")){
                   
              // }
               
               // registro[6] = rs.getString(7);
               // registro[7] = rs.getString(8);
                //registro[8] = rs.getString(9);
               // registro[9] = rs.getString(10);
                //registro[10] = rs.getString(11);
               // registro[11] = rs.getString(12);
               
               
           

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
   
}
 
 
 public void updateAviso(){
     
   // String[] titols = { "ID", "Num. empleado", "Num Cliente", "Num. JEFE", "Comments","Avisado"};
        String vSQL = new String();
      //  String[] registro = new String[6];

     //   modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
     
     vSQL = "UPDATE logA SET avisado='1' WHERE boss='"+numBoss+"';";
   try {
            Statement st = cn.createStatement();
            int rs = st.executeUpdate(vSQL);
           //st.executeQuery(vSQL);
            if (rs==1) {
                 
           // JOptionPane.showMessageDialog(this, "Avisos limpios");
          //   jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio2.gif")));
          //this.setVisible(false);
     
            }else{
             //  JOptionPane.showMessageDialog(this, "NO SE HA PODIDO REGISTRAR ");
            }
           
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
       }   
     
 
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cargarAvisoUser();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        updateAviso();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         int fila=jTableProductos.getSelectedRow();
        
        
        
        try {          
           fila=jTableProductos.getSelectedRow();

            if (fila==-1){
                JOptionPane.showMessageDialog(null,"SELECCIONA LA ORDER QUE QUIERES MODIFICAR");
            }         
            else{
             
               orderM=(String) jTableProductos.getValueAt(fila,0);
               modificarOrder mo=new modificarOrder();
               mo.setVisible(true);
           //   vPrecio=(String) jTableProductos.getValueAt(fila,3);
             // precio=Double.parseDouble(vPrecio);
              //cantidad=Integer.parseInt(jTextFieldCantidad.getText());
               
           
          
            }
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
       // jTableProductos.setValueAt(, linea, 5);
       // jTableProductos.setValueAt(combo1=new JComboBox());
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            
            LoginPrincipal llpp=new LoginPrincipal();
            
            llpp.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(classicmodels.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleadoJefeSupremo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleadoJefeSupremo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleadoJefeSupremo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleadoJefeSupremo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleadoJefeSupremo().setVisible(true);
            }
        });
    }
      
    public void consultarProductos() {

        //String[] titols = {"PRODUCTCODE", "PRODUCTNAME", "PRODUCTLINE", "PRODUCTSCALE","PRODUCTVENDOR","PRODUCTDESCRIPTION","QUANTITYINSTOCK","BUYPRICE","MSRP"};
        String[] titols = {"Nombre Producto","Descripción", "Stock","Precio"};
        String vSQL = new String();
        String[] registro = new String[4];

        modelo = new DefaultTableModel(null, titols);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT productName,productDescription,quantityInStock,buyPrice FROM products";// esto es lo que cambia

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("productName");
                registro[1] = rs.getString("productDescription");
                registro[2] = rs.getString("quantityInStock");
                registro[3] = rs.getString("buyPrice");
                

                modelo.addRow(registro);
            }
            jTableProductos.setModel(modelo);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAceptarBusqueda;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonVerProductos;
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmailUser;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
